README.md, buildAll.sh
=> build script to move jar into eclipse client

jakarta-eclipse/plugin.xml, jakarta-eclipse/src/org/jakarta/lsp4e/JakartaJavaHoverProvider.java, jakarta-eclipse/src/org/jakarta/lsp4e/JakartaLanguageClient.java, jakarta.ls/src/main/java/io/microshed/jakartals/JakartaLanguageServer.java, jakarta.ls/src/main/java/io/microshed/jakartals/JakartaTextDocumentService.java, jakarta.ls/src/main/java/io/microshed/jakartals/api/JakartaLanguageClientAPI.java
- Inserted hover dependency inside xml
- added hover function inside JakartaTextDocumentService.java for
service end
- modified the getJavaHover function inside
JakartaLanguageClientAPI.java (server side) and JakartaLanguageClient.java (client side) to return customized testing hover model
- added new hover JakartaJavaHoverProvider.java at client side to specify
the hovering style
=> Fixes #4 Hover implementation

jakarta-eclipse/plugin.xml, jakarta-eclipse/src/org/jakarta/lsp4e/extensions/JakartaJavaCompletionProposalComputer.java, jakarta.ls/src/main/java/io/microshed/jakartals/JakartaLanguageServer.java, jakarta.ls/src/main/java/io/microshed/jakartals/JakartaTextDocumentService.java, jakarta.ls/src/main/java/io/microshed/jakartals/commons/ISnippetContext.java, jakarta.ls/src/main/java/io/microshed/jakartals/commons/ISnippetRegistryLoader.java, jakarta.ls/src/main/java/io/microshed/jakartals/commons/JakartaEESnippetRegistryLoader.java, jakarta.ls/src/main/java/io/microshed/jakartals/commons/ProjectLabelInfoEntry.java, jakarta.ls/src/main/java/io/microshed/jakartals/commons/Snippet.java, jakarta.ls/src/main/java/io/microshed/jakartals/commons/SnippetContextForJava.java, jakarta.ls/src/main/java/io/microshed/jakartals/commons/SnippetDeserializer.java, jakarta.ls/src/main/java/io/microshed/jakartals/commons/SnippetRegistry.java, jakarta.ls/src/main/resources/jax-rs.json
This PR handles loading and parsing of JSON snippets into a SnippetRegistry which is invoked for completion items when the user requests autocompletion options.
=> Proof Of Concept for Snippets in Eclipse using Language Server

CONTRIBUTING.md, LICENSE, README.md
=> added license and contributing document

.gitignore, jakarta-eclipse/src/org/jakarta/jdt/JDTUtils.java, jakarta-eclipse/src/org/jakarta/jdt/JsonRpcHelpers.java, jakarta-eclipse/src/org/jakarta/jdt/ProjectUtils.java, jakarta-eclipse/src/org/jakarta/jdt/ResourceUtils.java, jakarta-eclipse/src/org/jakarta/lsp4e/JakartaLanguageClient.java
Added the JDT package with needed utilities and usage in diagnostics in JakartaLanguageClient to appear on every method in a class.
=> Added JDT tools and basic usage on Diagnostic

jakarta-eclipse/src/org/jakarta/jdt/DiagnosticsCollecter.java, jakarta-eclipse/src/org/jakarta/jdt/JDTServicesManager.java, jakarta-eclipse/src/org/jakarta/jdt/ServletDiagnosticsCollecter.java, jakarta-eclipse/src/org/jakarta/lsp4e/JakartaLanguageClient.java
there are following problems currently
- when changes happened on client side, the aync call makes the diagnostic msg does not update in time.
- get signature returned format in form "Q***;" which is the unresolved signature format in string. Not sure whether it is acceptable, might need trim.
=> webServlet diagnostics implementation (issue #7)

jakarta-eclipse/src/org/jakarta/jdt/DiagnosticsCollector.java, jakarta-eclipse/src/org/jakarta/jdt/JDTServicesManager.java, jakarta-eclipse/src/org/jakarta/jdt/ServletDiagnosticsCollector.java
Signed-off-by: PENGYUXIONG <pxiong@ualberta.ca>
=> fix typo again (issue #7)

jakarta-eclipse/src/org/jakarta/jdt/JDTServicesManager.java, jakarta-eclipse/src/org/jakarta/lsp4e/JakartaLanguageClient.java, jakarta.ls/src/main/java/io/microshed/jakartals/JakartaTextDocumentService.java, jakarta.ls/src/main/java/io/microshed/jakartals/api/JakartaLanguageClientAPI.java, jakarta.ls/src/main/java/io/microshed/jakartals/commons/SnippetRegistry.java, jakarta.ls/src/main/resources/servlet.json
Signed-off-by: AnkushSharma2698 <ankush1@ualberta.ca>
Closes #25
=> feat: added context based filtering for snippets

jakarta.ls/src/main/resources/servlet.json
Signed-off-by: AnkushSharma2698 <ankush1@ualberta.ca>
I decided against adding any extra functionality in the doFilter snippet because the use cases for this Filter are extremely varied and one snippet can not possibly cover the breadth of use cases. So keeping it as a clean snippet seemed most appropriate. 
This snippet has been tested with a demo-servlet application which has Jakarta included.
Closes #12
=> feat: created a generic filter snippet

jakarta-eclipse/src/org/jakarta/lsp4e/extensions/JakartaJavaCompletionProposalComputer.java, jakarta.ls/src/main/java/io/microshed/jakartals/commons/JakartaEESnippetRegistryLoader.java, jakarta.ls/src/main/resources/persistence.json
Signed-off-by: AnkushSharma2698 <ankush1@ualberta.ca>
closes #36 closes #35
=> feat: added snippets for persistencecontext and entity model

jakarta-eclipse/src/org/jakarta/jdt/JDTServicesManager.java, jakarta-eclipse/src/org/jakarta/jdt/ServletConstants.java, jakarta-eclipse/src/org/jakarta/jdt/diagnostics/DiagnosticsCollector.java, jakarta-eclipse/src/org/jakarta/jdt/diagnostics/FilterDiagnosticsCollector.java, jakarta-eclipse/src/org/jakarta/jdt/diagnostics/ListenerDiagnosticsCollector.java, jakarta-eclipse/src/org/jakarta/jdt/diagnostics/ServletDiagnosticsCollector.java
- add source, server, and serverity fields for existing diagnostics
- add complete diagnostic method implementention for diagnostic collector
=> complete fields for diagnostic (Issue #50)

jakarta-eclipse/src/org/jakarta/codeAction/CodeActionHandler.java, jakarta-eclipse/src/org/jakarta/codeAction/FilterImplementationQuickFix.java, jakarta-eclipse/src/org/jakarta/codeActionProposal/ImplementInterfaceProposal.java
- add in web filter implementation quick fix
- TODO: listener quick fix, annotation quick fixes
=> Add quick fixes for diagnostic (Issue #61)

jakarta-eclipse/src/org/jakarta/codeAction/CodeActionHandler.java, jakarta-eclipse/src/org/jakarta/codeAction/ListenerImplementationQuickFix.java, jakarta-eclipse/src/org/jakarta/jdt/diagnostics/ListenerDiagnosticsCollector.java
- Have implemented one implenmentation for each listener type
=> add listener quick fixes (Issue #61)

jakarta-eclipse/src/org/jakarta/jdt/BeanValidationDiagnosticsCollector.java, jakarta-eclipse/src/org/jakarta/jdt/JDTServicesManager.java
Added Digits, DecimalMax, DecimalMin, Email, PastOrPresent, FutureOrPresent, Past, Future, Min, Max, NegativeOrZero, PostiveOrZero, Negative, Positive, NotBlank, and Pattern annotation Diagnostics on field types, issue #53 
Also Added the static field diagnostics from #55 since it is related.
=> Added annotation Field type check diagnostics and static field diagnostics for BeanValidation 

jakarta-eclipse/src/org/jakarta/jdt/diagnostics/PersistenceEntityDiagnosticsCollector.java, jakarta-eclipse/src/org/jakarta/jdt/diagnostics/PersistenceMapKeyDiagnosticsCollector.java
=> Add source and severity to persistence diagnostics

.gitignore
Signed-off-by: Mandiiiiiii <mandyventurex7@gmail.com>
=> edit gitignore file

jakarta.ls/src/main/resources/jax-rs.json
Fixes #77 
Add snippets to quickly create JAX-RS POST, PUT, DELETE, HEAD methods.
=> Add snippets for new JAX-RS methods

README.md
=> Added badge for tests to README

README.md
=> Update Getting Started documentation in README

jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/cdi/ManagedBeanConstants.java, jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/cdi/ManagedBeanDiagnosticsCollector.java, jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/cdi/ManagedBeanQuickFix.java, jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/cdi/Utils.java
Signed-off-by: Hani Damlaj <hanidamlaj@gmail.com>
=> Refactor detecting managed beans into a reusable functional unit

jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/jax_rs/Jax_RSConstants.java, jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/jax_rs/ResourceMethodDiagnosticsCollector.java, jakarta-eclipse/org.eclipse.lsp4jakarta.tests/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/jax_rs/MultipleEntityParamsResourceMethod.java, jakarta-eclipse/org.eclipse.lsp4jakarta.tests/src/main/java/org/eclipse/lsp4jakarta/jdt/jax_rs/ResourceMethodTest.java
Add diagnostic and test for multiple entity parameters in resource method. See issue #117
=> Add diagnostic for multiple entity parameters in resource method

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/annotations/ResourceAnnotation.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/annotations/ResourceAnnotationTest.java
=> added resource annotation test

jakarta.eclipse/pom.xml, jakarta.jdt/pom.xml
=> Update tycho version and jdt ls version

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/annotations/PreDestroyAnnotation.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/annotations/PreDestroyAnnotationTest.java
=> 185 predestroy test

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/CodeActionHandler.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/quickfix/RemoveAbstractModifierQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/quickfix/RemoveFinalModifierQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/quickfix/RemoveInjectAnnotationQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/quickfix/RemoveModifierConflictQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/quickfix/RemoveStaticModifierQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/persistence/PersistenceEntityDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/persistence/PersistenceEntityQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/persistence/JakartaPersistenceTest.java
=> Refactoring for PersistenceEntityQuickFix.java

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/CodeActionHandler.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/.project, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/di/Greeting.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/di/GreetingNoDefaultConstructor.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/di/GreetingServlet.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/di/DependencyInjectionTest.java
Tests for: 
- Inject field non final diagnostic
- Inject method non final, non static, non abstract, non generic
Should close, #195, #221
=> Integration tests for Dependency Injection

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/CodeActionHandler.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JDTServicesManager.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/ConflictInjectMultipleConstructorQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/di/MultipleConstructorWithInject.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/di/MultipleConstructorInjectTest.java
Tests the diagnostic and quick fix for `@Inject` with Multiple Constructors.
Fixes #205.
Tests : #200.
=> DI: Tests for @Inject with Multiple Constructors

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/CodeActionHandler.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jax_rs/Jax_RSConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jax_rs/NoResourcePublicConstructorQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jax_rs/ResourceMethodDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jax_rs/RootResourceClassDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/jax_rs/NoPublicConstructorClass.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/jax_rs/ResourceClassConstructorTest.java
=> 116 resource class diagnostic quickfix

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/CodeActionHandler.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/ModifyModifiersProposal.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/quickfix/RemoveModifierConflictQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/cdi/RemoveInvalidInjectParamAnnotationQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/cdi/RemoveProduceAnnotationQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/cdi/InjectAndDisposesObservesObservesAsync.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/cdi/ProducesAndDisposesObservesObservesAsync.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/cdi/ManagedBeanTest.java
=> Added proposal and quick fix to remove annotations from parameters

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JDTServicesManager.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/servlet/ServletDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/websocket/WebSocketConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/websocket/WebSocketDiagnosticsCollector.java
Create a WebSocket package and add a constants class under the new package. This PR also adds the `@Override` annotation to the ServletDiagnosticsCollector class.
=> create websocket package

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/websocket/WebSocketConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/websocket/WebSocketDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/AnnotationTest.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/InvalidParamType.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/websocket/JakartaWebSocketTest.java
Resolves #248 
Example of functionality
=> Implemented onClose parameter type validation

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/RemoveMultipleAnnotations.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JDTUtils.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jsonb/JsonbConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jsonb/JsonbDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jsonb/JsonbTransientAnnotationQuickFix.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/jsonb/JsonbTransientDiagnostic.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/jsonb/JsonbDiagnosticsCollectorTest.java
=> Diagnostic for Accessor not having mutually exclusive JsonbTransient  annotations

jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/src/org/jakarta/lsp4e/JakartaLanguageClient.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/AbstractDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JDTServicesManager.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/annotations/AnnotationConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/annotations/AnnotationDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/servlet/FilterDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/servlet/ListenerDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/servlet/ServletConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/servlet/ServletDiagnosticsCollector.java
=> Validate Jakarta and Jakarta servlet annotations

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/AbstractDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/beanvalidation/BeanValidationConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/beanvalidation/BeanValidationDiagnosticsCollector.java
=> Filter BeanValidation diagnostics based on classpath/imports

.github/workflows/lsp4jakarta.yaml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/annotations/GeneratedAnnotation.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/annotations/PostConstructAnnotation.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/annotations/PreDestroyAnnotation.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/annotations/ResourceAnnotation.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/annotations/GeneratedAnnotationTest.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/annotations/ResourceAnnotationTest.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JakartaForJavaAssert.java
=> Automated tests failing on Windows

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/AbstractDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/persistence/PersistenceConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/persistence/PersistenceEntityDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/persistence/PersistenceMapKeyDiagnosticsCollector.java
=> Validate persistence annotations

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jax_rs/Jax_RSClassDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jax_rs/Jax_RSConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jax_rs/ResourceMethodDiagnosticsCollector.java
=> Validate JAXRS annotations

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/cdi/ManagedBeanConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/cdi/ManagedBeanDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/cdi/ManagedBeanTest.java
=> Validate cdi annotations

jakarta.ls/pom.xml
To resolve the error when initializing the lang server from jar
From:
To:
Screenshots taken on VS Code
=> update main class to ls launcher

jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/src/org/jakarta/lsp4e/JakartaLSConnection.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/Messages.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/annotations/AnnotationDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/resources/org/eclipse/lsp4jakarta/jdt/core/messages/messages.properties, jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/commons/SnippetRegistry.java, jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/utils/Messages.java, jakarta.ls/src/main/resources/org/eclipse/lsp4jakarta/messages/messages.properties, jakarta.ls/src/main/resources/servlet.json
=> Setup framework for translation.

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionDiagnosticsCollector.java
=> Validate "Inject" annotation

jakarta.ls/pom.xml, jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/JakartaLanguageServerLauncher.java
This assists other projects which use lsp4mp.ls version 0.5.0 and need to integrate lsp4jakarta. @kathrynkodama 
Fixes #327
=> Use lsp4mp.ls version 0.5.0 and update server launcher as required.

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/di/GreetingServlet.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/di/MultipleConstructorWithInject.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/jax_rs/NoPublicConstructorProviderClass.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/persistence/FinalModifiers.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/servlet/DontExtendHttpServlet.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/AnnotationTest.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/InvalidParamType.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/di/DependencyInjectionTest.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/di/MultipleConstructorInjectTest.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/jax_rs/ResourceClassConstructorTest.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/persistence/JakartaPersistenceTest.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/servlet/JakartaServletTest.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/websocket/JakartaWebSocketTest.java
=> Fix test compile issues

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JDTServicesManager.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/transactions/TransactionsConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/transactions/TransactionsDiagnosticsCollector.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/websocket/WebSocketConstants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/websocket/WebSocketDiagnosticsCollector.java
=> Validate WebSocket annotations

jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/plugin.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/src/org/jakarta/lsp4e/JakartaLanguageClient.java, jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/JakartaTextDocumentService.java, jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/api/JakartaLanguageClientAPI.java
=> Remove getJavaHover API

.github/workflows/lsp4jakarta.yaml, docs/BUILDING.md, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/META-INF/MANIFEST.MF, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.test/META-INF/MANIFEST.MF, jakarta.eclipse/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/META-INF/MANIFEST.MF, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/META-INF/MANIFEST.MF, jakarta.jdt/pom.xml
=> Java 17 support

jakarta.ls/pom.xml, jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/commons/SnippetRegistry.java
=> Update jakarta.ls Maven target and lsp4j versions

jakarta.ls/src/main/resources/jax-rs.json, jakarta.ls/src/main/resources/persistence.json, jakarta.ls/src/main/resources/servlet.json
=> Fix inconsistent variable names in JSON files

jakarta.ls/pom.xml
=> Update lsp4j to 0.17.0

jakarta.ls/src/main/resources/persistence.json, jakarta.ls/src/main/resources/servlet.json, jakarta.ls/src/main/resources/transactions.json
=> Shorten code snippet descriptions

NOTICE.md, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/META-INF/MANIFEST.MF, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.feature/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.site/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.test/META-INF/MANIFEST.MF, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.test/pom.xml, jakarta.eclipse/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/META-INF/MANIFEST.MF, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/plugin.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.site/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/META-INF/MANIFEST.MF, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/pom.xml, jakarta.jdt/pom.xml, jakarta.ls/pom.xml
Some updates to the project pom files and bundle info for #333 
=> Update project pom and bundle info

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JDTServicesManager.java, jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/commons/SnippetRegistry.java
=> Resolve snippet package and class name variables

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JDTServicesManager.java
Method:  List<String> getExistingContextsFromClassPath()
Please review @kathrynkodama and @bensonnw 
Signed-off-by: Paul Gooderham <turkeyonmarblerye@gmail.com>
=> After exception maintain length of list in method

jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/JakartaTextDocumentService.java
=> User input left in when snippet is selected

README.md, docs/CONTRIBUTING.md, jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/commons/JakartaEESnippetRegistryLoader.java, jakarta.ls/src/main/resources/bean-validation.json, jakarta.ls/src/main/resources/persistence.json, jakarta.ls/src/main/resources/restfulWs.json, jakarta.ls/src/main/resources/servlet.json, jakarta.ls/src/main/resources/transactions.json
Fixes #336 
Partially addresses #350, adds documentation to the README detailing each snippet for end users, and how to contribute new snippets to the Contributing doc. 
https://github.com/kathrynkodama/lsp4jakarta/tree/336-snippet#jakarta-ee-api-language-features
=> Update snippet names, prefixes and descriptions

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/META-INF/MANIFEST.MF
=> Fix Eclipse LSp4Jakarta JDT Test Plugin name

Jenkinsfile, jakarta.jdt/pom.xml
Should allow the Jenkins instance to build `main` when PR is merged.
=> Add Jenkinsfile and signing profile for snapshot builds

Jenkinsfile
=> Fix syntax error in Jenkinsfile

Jenkinsfile
=> Fix build commands in Jenkinsfile

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JDTUtils.java
=> Rollback the code to sync up CU and underlying resource

Jenkinsfile, jakarta.eclipse/.mvn/wrapper/maven-wrapper.properties, jakarta.eclipse/mvnw, jakarta.eclipse/mvnw.cmd, jakarta.jdt/.mvn/wrapper/maven-wrapper.properties, jakarta.jdt/mvnw, jakarta.jdt/mvnw.cmd, jakarta.ls/.mvn/wrapper/maven-wrapper.properties, jakarta.ls/mvnw, jakarta.ls/mvnw.cmd
=> Adding Maven wrapper for Jenkins builds

Jenkinsfile, jakarta.eclipse/pom.xml, jakarta.jdt/pom.xml, jakarta.ls/pom.xml
=> Add Eclipse cbi plugin repo

Jenkinsfile
=> Add debug for Jenkins Maven builds

jakarta.jdt/pom.xml
=> Try changing tycho useUIHarness flag

Jenkinsfile, jakarta.ls/pom.xml
=> Enabling publishing snapshots via Jenkinsfile

Jenkinsfile, jakarta.jdt/pom.xml
=> Publish JDT artifacts to repo.eclipse.org

jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/commons/SnippetRegistry.java
=> Fix snippet indentation issue

jakarta.ls/src/main/resources/persistence.json
=> Fix the placeholder

Jenkinsfile
=> Reorder JDT Extension snapshot deployments

jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/JakartaTextDocumentService.java, jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/commons/SnippetRegistry.java
=> Add a filter for getting completion items

jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/JakartaTextDocumentService.java
Remove unused hover code, part of https://github.com/eclipse/lsp4jakarta/issues/323
=> Remove leftover unused hover code

jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/JakartaTextDocumentService.java
Reverts eclipse/lsp4jakarta#387
=> Revert "Remove leftover unused hover code"

jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/META-INF/MANIFEST.MF, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.feature/feature.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.feature/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.site/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.test/META-INF/MANIFEST.MF, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.test/pom.xml, jakarta.eclipse/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/META-INF/MANIFEST.MF, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.site/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/META-INF/MANIFEST.MF, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/pom.xml, jakarta.jdt/pom.xml, jakarta.ls/pom.xml
=> Bump to 0.1.0-SNAPSHOT

Release.Jenkinsfile
=> Adding Release.Jenkinsfile

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/pom.xml, jakarta.jdt/pom.xml
=> Bump JDT LS version to 1.19.0-SNAPSHOT

jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/src/org/eclipse/lsp4jakarta/lsp4e/JakartaLanguageClient.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JDTServicesManager.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/core/ls/JakartaDelegateCommandHandlerForJava.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JakartaForJavaAssert.java
Reverts eclipse/lsp4jakarta#392
=> Revert "Change class JDTServicesManager to PropertiesManagerForJava"

Release.Jenkinsfile
=> Add jarsigner to release lsp4jakarta.jdt

Release.Jenkinsfile
=> Comment out jakarta.ls publishing

Release.Jenkinsfile
=> Version fix in release jenkinsfile

Release.Jenkinsfile
=> tycho version releasejenkinsfile

Release.Jenkinsfile
=> Remove deploy to repo release

Release.Jenkinsfile
=> Revert Release.Jenkinsfile to working state

jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.feature/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.site/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.test/pom.xml, jakarta.eclipse/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.site/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/pom.xml, jakarta.jdt/pom.xml, jakarta.ls/pom.xml
=> version 0.1.0

jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/META-INF/MANIFEST.MF, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.feature/feature.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.feature/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.site/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.test/META-INF/MANIFEST.MF, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.test/pom.xml, jakarta.eclipse/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/META-INF/MANIFEST.MF, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.site/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/META-INF/MANIFEST.MF, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/pom.xml, jakarta.jdt/pom.xml, jakarta.ls/pom.xml
=> Prepare for next development iteration 0.1.1-SNAPSHOT

Release.Jenkinsfile, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.test/META-INF/MANIFEST.MF
=> Fix for jakarta.eclipse Fragment-Host

buildAll.sh
Workaround for issue #440 to use in the meantime.
=> "Workaround 'mvn clean install' issue with 'mvn clean; mvn install'"

jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/JakartaTextDocumentService.java
Investigated related methods but none of them return nulls which are used.
=> Check document for null before use.

jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/snippets/SnippetContextForJava.java
=> Do not suggest method or field snippets before a class statement.

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/cdi/ManagedBeanTest.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/di/DependencyInjectionTest.java
Fixes #477
Keep in sync with update in intellij proj.
=> Add headers to certain test files.

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jax_rs/ResourceMethodDiagnosticsCollector.java
=> Fix invalid diagnostic on valid interface method

Release.Jenkinsfile, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/pom.xml, jakarta.ls/pom.xml
- Reordered build steps in Release.Jenkinsfile to follow project dependency order
- Updated project dependencies to the next release version
=> Reorder build steps in Release.Jenkinsfile and update dependencies

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/jaxrs/ResourceClassConstructorTest.java
=> Add missing JAX-RS code action tests

jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/ls/JakartaLanguageServer.java
Implemented the method `setTrace()` in the interface `LanguageServer` in the class `JakartaLanguageServer`.
#530
=> Unsupported Operation Exception in Language Servers - Fixes #530

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/persistence/RemoveMapKeyAnnotationsQuickFix.java
=> Fixed #446

jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/pom.xml, jakarta.ls/pom.xml
Prepare for the release build.
=> Use release 0.2.2 in pom.xml

Release.Jenkinsfile
=> Release 2.2

jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/pom.xml, jakarta.ls/pom.xml
=> Change the dependencies in pom

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/beanvalidation/BeanValidationDiagnosticsParticipant.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/beanvalidation/Constants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/beanvalidation/BeanValidationTest.java
Fixes #524 
Code modifications have been made to incorporate the @PositiveOrZero annotation, also enabled test case to handle it.
=> Fix and test cases added for PositiveOrZero annotation

jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/META-INF/MANIFEST.MF, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.feature/feature.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.feature/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.site/pom.xml, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.test/META-INF/MANIFEST.MF, jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.test/pom.xml, jakarta.eclipse/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/META-INF/MANIFEST.MF, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.site/pom.xml, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/META-INF/MANIFEST.MF, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/pom.xml, jakarta.jdt/pom.xml, jakarta.ls/pom.xml
Update the version numbers for the 0.2.3 release. This pull request includes the manually updated pom dependencies not updated by the tycho Maven plugin.
=> Release 0.2.3

RELEASE.md
Instructions for the next person to create a release for this project. Best to keep this document with the code.
=> Release process documentation

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/utils/TypeHierarchyUtils.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/DiagnosticUtils.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/beanvalidation/BeanValidationDiagnosticsParticipant.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/beanvalidation/Constants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/cdi/ManagedBeanDiagnosticsParticipant.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/servlet/Constants.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/servlet/ServletDiagnosticsParticipant.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/beanvalidation/ValidConstraints.java, jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/cdi/ProducesAndDisposesObservesObservesAsync.java
defect link = #577 
This defect was identified as part of the investigation I performed while analysing #507 
Addressing both scenarios which mentioned in the 577
=> The system is unable to detect the fully qualified name and is providing incorrect diagnostics.

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/test/beanvalidation/BeanValidationTest.java
This PR is related to issue #528. Fixed a minor in the argument passed.
=> Decimal Min annotation minor fix

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/plugin.xml
This is to address the issue #560 
The test cases for this is addressed in the PR https://github.com/eclipse-lsp4jakarta/lsp4jakarta/pull/594
=> Missing Code Action for @WebFilter() Diagnostic in Eclipse
