eclipse-lsp4jakarta/lsp4jakarta

jakarta-eclipse/src/org/jakarta/jdt/JDTServicesManager.java
jakarta-eclipse/src/org/jakarta/lsp4e/JakartaLanguageClient.java

- Minor formatting
- reuse the same instance of `JDTServicesManager` 
- disable test hover

Reuse same instance of JDTServicesManager and disable test hover

---

jakarta.ls/src/main/java/io/microshed/jakartals/commons/JakartaEESnippetRegistryLoader.java
jakarta.ls/src/main/resources/bean-validation.json

Bean validation email string field snippet on the @Email built-in constraint annotation.
[https://jakarta.ee/specifications/bean-validation/3.0/jakarta-bean-validation-spec-3.0.html#builtinconstraints-email](https://jakarta.ee/specifications/bean-validation/3.0/jakarta-bean-validation-spec-3.0.html#builtinconstraints-email)

Added Bean validation @Email snippet

---

jakarta.ls/src/main/resources/jax-rs.json

Change the used namespace from javax.* to jakarta.* in JAX-RS resource class and method snippets.

 Change used namespace from javax.* to jakarta.* in JAX-RS snippets

---

.gitignore
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/codeAction/CodeActionHandler.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/codeAction/JavaCodeActionContext.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/codeAction/proposal/ReplaceAnnotationProposal.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/JDTServicesManager.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/cdi/ManagedBeanConstants.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/cdi/ManagedBeanDiagnosticsCollector.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/cdi/ManagedBeanQuickFix.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/servlet/InsertAnnotationMissingQuickFix.java
jakarta-eclipse/org.eclipse.lsp4jakarta.tests/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/cdi/ManagedBean.java
jakarta-eclipse/org.eclipse.lsp4jakarta.tests/src/main/java/org/eclipse/lsp4jakarta/jdt/cdi/ManagedBeanTest.java

Fixes #81
"If a managed bean has a non-static public field, it must have scope @Dependent. If a managed bean with a non-static public field declares any scope other than @Dependent, the container automatically detects the problem and treats it as a definition error." [Managed Bean Spec](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#managed_beans)
- Annotated "@Dependent" with non-static public field(s); no errors.
- Annotated "@Dependent" & "@ApplicationScoped" with non-static public field(s); shows errors.
- Annotated "@ApplicationScoped" with non-static public field(s); shows errors.
- Annotated "@ApplicationScoped" with **static** public field(s); no errors;
- Currently no logic implemented to recognise a managed bean other than annotations. Specifically, we don't detect …

Add diagnostics for Managed Beans

---

jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/codeAction/CodeActionHandler.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/codeAction/proposal/quickfix/RemoveAnnotationConflictQuickFix.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/jsonb/JsonbAnnotationQuickFix.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/jsonb/JsonbConstants.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/jsonb/JsonbCreatorDiagnosticsCollector.java
jakarta-eclipse/org.eclipse.lsp4jakarta.tests/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/jsonb/ExtraJsonbCreatorAnnotations.java
jakarta-eclipse/org.eclipse.lsp4jakarta.tests/src/main/java/org/eclipse/lsp4jakarta/jdt/jsonb/JsonbTest.java

Fixes #95 
Added quickfix for jsonbcreator errors to add a "Remove annotation" quickfix to each jsonbcreator annotation (there should only be one)
Added a code, source, and severity to the diagnostic.
Also added tests for the diagnostic and quickfix

95 jsonbcreator quickfix

---

jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/cdi/ManagedBeanConstants.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/cdi/ManagedBeanDiagnosticsCollector.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/cdi/Utils.java
jakarta-eclipse/org.eclipse.lsp4jakarta.tests/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/cdi/ManagedBean.java
jakarta-eclipse/org.eclipse.lsp4jakarta.tests/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/cdi/ScopeDeclaration.java
jakarta-eclipse/org.eclipse.lsp4jakarta.tests/src/main/java/org/eclipse/lsp4jakarta/jdt/cdi/ManagedBeanTest.java
jakarta-eclipse/org.eclipse.lsp4jakarta.tests/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JakartaForJavaAssert.java

Fix issue #103 
From https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#declaring_bean_scope:
"A bean class or producer method or field may specify at most one scope type annotation. If a bean class or producer method or field specifies multiple scope type annotations, the container automatically detects the problem and treats it as a definition error."
- Ordering of the diagnostic within the actual and expected lists shouldn't affect equality – added support for ordering the two lists by the start and end ranges before comparing for equality
previously, assertDiagnostics would report the following error for two lists of identical diagnostics (fields of the diagnostic for brevity) due to the ordering within the list:
```
Failures:
ManagedBeanTest.producesAndInject:70 …
```

Declaring bean scope

---

jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/codeAction/CodeActionHandler.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/codeAction/proposal/ModifyModifiersProposal.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/codeAction/proposal/RemoveEntityParamsProposal.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/codeAction/proposal/RemoveParamsProposal.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/jax_rs/NonPublicResourceMethodQuickFix.java
jakarta-eclipse/org.eclipse.lsp4jakarta.core/src/org/jakarta/jdt/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java
jakarta-eclipse/org.eclipse.lsp4jakarta.tests/src/main/java/org/eclipse/lsp4jakarta/jdt/jax_rs/ResourceMethodTest.java

Closes #132 
If there exists more than one entity parameter in a resource method, add quick fixes for each of the entity parameters which removes all entity parameters except that one.
For diagnostic #131

Add quick fixes to remove entity params in resource method

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/servlet/FilterDiagnosticsCollector.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/servlet/ServletDiagnosticsCollector.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/servlet/JakartaServletTest.java

We do not have enough type hierarchy information to definitely say that the user is not extended/implementing the correct class/interface.

Lower WebServlet (#159) and WebFilter (#13) diagnostics to warning severity

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JDTUtils.java

See my [comment](https://github.com/eclipse/lsp4jakarta/issues/26#issuecomment-954398977) in issue #26.
I decided to put the loop in `JDTUtils.resolveCompilationUnit()` so that anything that uses it has a consistent `ICompilationUnit`. I set the while loop timeout to 3 seconds, just in case.

Fixed keystroke delay (#26)

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/CodeActionHandler.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionConstants.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionDiagnosticsCollector.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/RemoveAbstractModifierQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/RemoveStaticModifierQuickFix.java

Should close #168
Diagnostic for abstract/final/static/generic method(s) with `@Inject`
Quick fix to either remove `@Inject` annotation or the modifier(s)
Integration tests to be added in a later patch

DI: diagnostic and quick fix for final/abstract injectable methods

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/CodeActionHandler.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/cdi/ManagedBeanDiagnosticsCollector.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/cdi/ManagedBeanNoArgConstructorQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/cdi/ManagedBeanConstructorTest.java

Provide one quickfix for #191
> Suggest adding snippet code to declare no-arg constructor

Added quickfix to create no-arg constructor for managed beans

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/cdi/ManagedBeanConstants.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/cdi/ManagedBeanDiagnosticsCollector.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionConstants.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionDiagnosticsCollector.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/cdi/ManagedBean.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/cdi/ManagedBeanTest.java

 Added diagnostics and quickfix for a managed bean class of generic type

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/TypeHierarchyUtils.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/servlet/ServletDiagnosticsCollector.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/di/GreetingServlet.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/servlet/JakartaServletTest.java

**DRAFT:** The tests for @WebServlet diagnostics fail because my fix will report a diagnostic that the WebServlet class does not extend `HttpServlet` when in fact it does. This is because under the test environment `typeHierarchy.getAllSupertypes(type);` is empty. I've tried the test code in my eclipse instance with my change and no diagnostic is reported.

Added type hierarchy check for @WebServlet diagnostic (#159)

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JDTUtils.java

This is needed for #240 and #242.
This PR creates a method in JDTUtils for checking if a string starts with a `/`.

Add method to verify URIs have a leading slash

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JDTUtils.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/websocket/WebSocketConstants.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/websocket/WebSocketDiagnosticsCollector.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/ServerEndpointDuplicateVariableURI.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/ServerEndpointInvalidTemplateURI.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/ServerEndpointNoSlash.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/ServerEndpointRelativePathTest.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/websocket/JakartaWebSocketTest.java

Resolves #240 
Create methods to:
+ Verify URIs have a leading slash (done in #263)
+ Verify that a URI is following a valid URI template (level 1)
+ Verify that a URI is not using duplicate variables
+ Verify that URIs are not using relative paths
These first two methods are located in JDTUtils so that other packages can access them for ease of use.

Add diagnostic support for ServerEndpoint URI validation

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/websocket/WebSocketConstants.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/websocket/WebSocketDiagnosticsCollector.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/DuplicateOnMessage.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/websocket/JakartaWebSocketTest.java

Resolves #243
Show diagnostics if a duplicate method is found for a @onMessage method for the same message format (text, binary, or pong).

add diagnostics for duplicate onMessage methods

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/CodeActionHandler.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/ModifyReturnTypeProposal.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/annotations/PostConstructReturnTypeQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/annotations/PostConstructAnnotation.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/annotations/PostConstructAnnotationTest.java

Resolves #227. Also resolves the second part of #183 (the quick fix "change return type to void" for the PostConstruct diagnostic).
Add a proposal that modifies the return type of a method. A quick fix on the return type of PostConstruct annotated-methods is also added using this proposal.

Add ModifyReturnTypeProposal and quick fix for PostConstruct annotated-methods

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/DuplicateOnMessage.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/ServerEndpointDuplicateVariableURI.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/ServerEndpointInvalidTemplateURI.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/ServerEndpointNoSlash.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websocket/ServerEndpointRelativePathTest.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/websockets/PathParamURIWarningTest.java

Addresses remaining compile issues in `lsp4jakarta/jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects`.
Fixes #294

Fix test project package statements

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/cdi/ManagedBeanDiagnosticsCollector.java

Signed-off-by: Paul Gooderham <turkeyonmarblerye@gmail.com>
Fixes #359 
@kathrynkodama  @bensonnw  please review this fix. Originally found in the IntelliJ code.

Check the return of getMatchedJavaElementName for null.

---

jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/src/org/eclipse/lsp4jakarta/lsp4e/JakartaLanguageClient.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/PropertiesManagerForJava.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/core/ls/JakartaDelegateCommandHandlerForJava.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/core/JakartaForJavaAssert.java

In issue https://github.com/OpenLiberty/liberty-tools-intellij/issues/191 we see a problem identifying changes related to the language server component versus the Java analysis (JDT) component. When JDTServicesManager was created it was a version of a class called PropertiesManagerForJava. With this pull request we restore that name and make it similar to the naming convention in other language server projects. This should make it easier to port changes from one project to another. 
Signed-off-by: Paul Gooderham <turkeyonmarblerye@gmail.com>

Change class JDTServicesManager to PropertiesManagerForJava

---

jakarta.ls/pom.xml

This version includes the Maven descriptor of the artifact itself, i.e.
> META-INF/maven/org.eclipse.lsp4jakarta/org.eclipse.lsp4jakarta.ls/pom.xml
> META-INF/maven/org.eclipse.lsp4jakarta/org.eclipse.lsp4jakarta.ls/pom.properties
Also it is less verbose, and so quicker.

Upgrade assembly-plugin in jakarta.ls

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/RemoveMultipleAnnotations.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/quickfix/InsertAnnotationMissingQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/codeAction/proposal/quickfix/RemoveAnnotationConflictQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/cdi/ManagedBeanNoArgConstructorQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/cdi/ScopeDeclarationQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jax_rs/NoResourcePublicConstructorQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jax_rs/NonPublicResourceMethodQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/persistence/PersistenceEntityQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/servlet/FilterImplementationQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/servlet/HttpServletQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/servlet/ListenerImplementationQuickFix.java

Fixes #449
Fixes the exception `Cannot invoke "java.util.Collection.toArray()" because "<parameter1>" is null`
In each case we run code like:
`codeActions.addAll(AddPathParamQuickFix.getCodeActions(context, diagnostic, monitor));`
and null is not a valid arg to `addAll()`. This usually does not happen because usually the program is well formed and if the diagnostic can be detected then a quick fix can be created. However in some cases syntax errors are too severe and the quick fix creation fails and a null may be returned.

Ensure getCodeActions() always returns a list and not null.

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/demo-servlet-no-diagnostics/pom.xml
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/pom.xml
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/liberty/config/server.xml

Don't need to use the beta Open Liberty with the newest Liberty versions that will be installed by default.  Also update to latest liberty-maven-plugin version.

Update liberty-maven-plugin config in test projects for latest version

---

jakarta.eclipse/pom.xml
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/demo-servlet-no-diagnostics/pom.xml
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/pom.xml
jakarta.jdt/pom.xml
jakarta.ls/pom.xml

This PR:
- Updates the JUnit dependency version to fix maven repository reported vulnerability (lsp4jakarta.ls).
- Updates the Liberty Maven Plugin version used by test projects. 
- Cleanup.

Update junit dependency version

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/META-INF/MANIFEST.MF

Without this I hit a ClassCastException when trying to resolve a code action from the LSP4MP.
I was running into a scenario where one path resolved the code action data directly from the lsp4e bundle and the other path accessed it via my "client" bundle.  The client also packages the "commons*" classes, but if we export them from jakarta.jdt we will consistently load them from this bundle rather than using our local client-packaged classes.
Leaving aside the other difficulties with the LSP4MP code action above, it seemed like this could be fixed independently.

Export all commons.* packages from jakarta.jdt bundle

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/DiagnosticUtils.java

this PR will resolve liberty-tools-vscode issue:
https://github.com/OpenLiberty/liberty-tools-vscode/issues/322

eliminate the usage of jdt internal API to get list of imports

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/plugin.xml
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/commons/codeaction/JakartaCodeActionId.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/java/corrections/proposal/ModifyAnnotationProposal.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/annotations/AnnotationDiagnosticsParticipant.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/annotations/Constants.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/annotations/ErrorCode.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/annotations/InsertDefaultResourceAnnotationToResourcesAnnotation.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/resources/org/eclipse/lsp4jakarta/jdt/core/messages/messages.properties
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/annotations/ResourceAnnotation.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/annotations/ResourcesAnnotation.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/annotations/ResourceAnnotationTest.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/annotations/ResourcesAnnotationTest.java

add quickfix fn to handle composite annotations

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/cdi/ErrorCode.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/cdi/ManagedBeanDiagnosticsParticipant.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/resources/org/eclipse/lsp4jakarta/jdt/core/messages/messages.properties
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/cdi/ManagedBeanTest.java

We clarified this rule with the Liberty CDI team and decided the latest added diagnostic is not correct. The fix for the original diagnostic is correct. The issue #534 has a bit more explanation.
https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#managed_beans
Fixes #534

Remove diagnostic for managed bean public field with invalid scope

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/beanvalidation/RemoveDynamicConstraintAnnotationQuickFix.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/core/ls/ArgumentUtils.java

Fixes #416 
Quick-fix fails due to getData() is null.
The root cause of the issue is lsp4Jakarta expects a Map object from VS Code, but we are sending a string or array of strings from VS code. Resolved the null pointer exception by adding code to handle both the 'data' format.
eg:
data = “AssertTrue”
data =[“ApplicationScoped", "RequestScoped”]

Fixes #416 - Quick-fix fails due to getData() is null

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/plugin.xml
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/cdi/ManagedBeanTest.java

Pull request #511 added a quick fix which removes all three annotations from a parameter when some of the annotations are in conflict. E.g. "@Disposes @Observes @ObservesAsync String name" There should be two quick fixes, one that removes @Disposes and one that removes @Observes and @ObservesAsync. 
In this pull request we temporarily remove the quick fix from two situations along with the tests that validate them. There is an issue open to fix the code so we can restore the quick fix.

Remove a quick fix that removes both annotations when the two are mutually exclusive

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/core/ls/ArgumentUtils.java

Fixes #541 
Remove the recently added log statement used to track code action data received on the Jakarta server. This log prints frequently in the VS Code console, and when the log level is changed to debug, it does not appear in the console despite the trace being set to "verbose."

Removed the log statement added to track the code action data received in Jakarta server.

---

.idea/.gitignore
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/servlet/DontImplementFilter.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/servlet/DontImplementListener.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/servlet/JakartaServletTest.java

this is to fix the issue https://github.com/eclipse-lsp4jakarta/lsp4jakarta/issues/521
Added test cases to support the mentioned cases.

Tests for InsertImplementsClauseToImplFilterQuickFix and InsertImplementsClauseToImplListenerQuickFix is not available in lsp4jakarta

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/commons/JavaCursorContextKind.java
jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/commons/JavaCursorContextKind.java

The PR addresses Issue: https://github.com/eclipse-lsp4jakarta/lsp4jakarta/issues/520
Root causes were observed in JavaCursorContextKind.java files in 
>lsp4jakarta.ls
>lsp4jakarta.jdt

Fix to address JavaCursorContextKind IllegalArgumentException

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/persistence/ErrorCode.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/persistence/PersistenceMapKeyDiagnosticsParticipant.java
jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/resources/org/eclipse/lsp4jakarta/jdt/core/messages/messages.properties

Fix for: https://github.com/eclipse-lsp4jakarta/lsp4jakarta/issues/532
Add new diagnostics for MapKey annotations
1) Check Access Specifier is public and following JavaBean Accessor naming conventions
2) Check return type of Field or Method is a Map type

Add new diagnostics for MapkeyAnnotations: Access Specifier and Type check

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/commons/JavaCursorContextKind.java
jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/commons/JavaCursorContextKind.java
jakarta.ls/src/test/java/org/eclipse/lsp4jakarta/snippets/JakartaSnippetRegistryTest.java

This PR is to sync up the enum value change made in lsp4mp (https://github.com/eclipse-lsp4mp/lsp4mp/pull/502) as part of lsp4jakarta issue (https://github.com/eclipse-lsp4jakarta/lsp4jakarta/issues/520)

Fixes issue #520:  Changed value of NONE type to keep in sync with lsp4mp

---

jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/test/servlet/JakartaServletTest.java

Fixes for issue https://github.com/eclipse-lsp4jakarta/lsp4jakarta/issues/232
getAllSupertypes()  related fixes(jrt-fs.jar missing in class path issue) already covered in PR https://github.com/eclipse-lsp4jakarta/lsp4jakarta/pull/578

Fix: getAllSupertypes() returns nothing under test environment
